"""
Jarvis Business Context
=======================

What Jarvis KNOWS about the money-making setup, in one place, so that
(a) his chat brain can talk about it accurately instead of guessing,
(b) voice/text commands like "check fiverr" or "open redbubble" know where
    to go, and
(c) the HUD can show the same list.

Deliberately its own small module with no heavy imports so it can be
tested without starting Jarvis. The facts below are a hand-kept snapshot
(see FACTS_AS_OF) -- Jarvis cannot see inside Fiverr/Redbubble/AdSense on
his own, so anything live (orders, messages, earnings) must be checked by
actually opening those pages, never assumed from this list.
"""

import re

import jarvis_business as jbiz

FACTS_AS_OF = "2026-10-02"

CHANNELS = [
    {
        "key": "fiverr_gigs", "name": "Fiverr gigs", "url": "https://www.fiverr.com/users/danielhoole/manage_gigs",
        "what": "Danny's Fiverr seller account (danielhoole). Four gigs are live: SEO blog posts, "
                "SEO product descriptions, plain-English research briefs, and email newsletter issues.",
    },
    {
        "key": "fiverr_orders", "name": "Fiverr orders", "url": "https://www.fiverr.com/users/danielhoole/manage_orders",
        "what": "Real orders only ever appear here. As of the snapshot there were none.",
    },
    {
        "key": "fiverr_inbox", "name": "Fiverr messages", "url": "https://www.fiverr.com/inbox",
        "what": "Buyer messages. WARNING: the first four messages received were scams (fake 'I already placed "
                "an order' plus links or an .html attachment). Never open those links or files.",
    },
    {
        "key": "redbubble", "name": "Redbubble shop", "url": "https://www.redbubble.com/studio/dashboard",
        "what": "Print-on-demand shop 'northwichstudio'. Live designs: Coastal Fog poster, Santa's Workshop, "
                "Santa's Flying Sleigh (the last two are Danny's wife's artwork). A retro mushroom cottage "
                "pattern was generated by Jarvis but not yet uploaded.",
    },
    {
        "key": "blog", "name": "Jarvis blog", "url": "https://jarvis-blog-8gb.pages.dev",
        "what": "Autonomous article blog, 10 articles published by the business loop. Has Google AdSense "
                "installed (awaiting Google's approval) and Cloudflare Web Analytics.",
    },
    {
        "key": "adsense", "name": "Google AdSense", "url": "https://adsense.google.com/adsense/u/0/pub-7727211964805136/",
        "what": "Ad earnings for the blog. Publisher ID ca-pub-7727211964805136. Not earning until Google approves the site.",
    },
    {
        "key": "search_console", "name": "Google Search Console",
        "url": "https://search.google.com/search-console?resource_id=https%3A%2F%2Fjarvis-blog-8gb.pages.dev%2F",
        "what": "Blog is verified and sitemap.xml was submitted on 2026-10-02 (first status read 'Couldn't fetch' -- recheck).",
    },
    {
        "key": "analytics", "name": "Blog analytics",
        "url": "https://dash.cloudflare.com/8cfdbd742f6104cc10eec937f45d3710/web-analytics",
        "what": "Cloudflare Web Analytics for the blog. Jarvis reads page views from here automatically each business cycle.",
    },
]

_BY_KEY = {c["key"]: c for c in CHANNELS}

# Spoken phrase -> channel key, for "open ..." requests. Exact matches only,
# so an ordinary "open chrome" is never hijacked.
_OPEN_SYNONYMS = {
    "fiverr orders": "fiverr_orders", "my fiverr orders": "fiverr_orders", "orders": "fiverr_orders",
    "fiverr messages": "fiverr_inbox", "fiverr inbox": "fiverr_inbox", "fiverr chat": "fiverr_inbox",
    "fiverr": "fiverr_gigs", "fiverr gigs": "fiverr_gigs", "my gigs": "fiverr_gigs", "gigs": "fiverr_gigs",
    "redbubble": "redbubble", "redbubble shop": "redbubble", "redbubble dashboard": "redbubble",
    "search console": "search_console", "google search console": "search_console",
    "adsense": "adsense", "google adsense": "adsense",
    "blog": "blog", "my blog": "blog", "the blog": "blog", "jarvis blog": "blog",
    "analytics": "analytics", "blog analytics": "analytics", "web analytics": "analytics",
}

_OPEN_RE = re.compile(
    r"^(?:please |can you |could you |jarvis |jay )*(?:open|show|go to|take me to|pull up)"
    r"(?: me)?(?: up)?(?: my| the)? (?P<what>[a-z ]+?)$"
)
_CHECK_FIVERR_RE = re.compile(
    r"\b(?:check|read|look at|look in|any|anything|new|have i got|do i have|did i get|what'?s on|what is on)\b"
    r".*\bfiverr\b.*\b(?:orders?|messages?|inbox|jobs?|gigs?|chats?)?\b"
    r"|\bfiverr\b.*\b(?:orders?|messages?|inbox|jobs?)\b.*\b(?:check|any|new|yet)\b"
    r"|\b(?:check|read) (?:my )?fiverr\b"
)
_LIST_RE = re.compile(
    r"\b(?:what(?:'s| is| have we got| do we have| are we) (?:set up|selling|going on with the business|"
    r"running)|where are we selling|what channels|business overview|what businesses|"
    r"what('?s| is) going on with (?:the )?(?:business|money|income)|what income streams)\b"
)


def channel_url(key):
    channel = _BY_KEY.get(key)
    return channel["url"] if channel else None


def parse_channel_request(command):
    """
    Returns ("open", key), ("check_fiverr", None), ("list", None), or None
    when the command isn't about the business channels at all.
    """
    c = re.sub(r"[^a-z0-9' ]+", " ", str(command or "").lower()).strip()
    c = re.sub(r"\s+", " ", c)
    if not c:
        return None

    if _LIST_RE.search(c):
        return ("list", None)

    match = _OPEN_RE.match(c)
    if match:
        what = match.group("what").strip()
        key = _OPEN_SYNONYMS.get(what)
        if key:
            return ("open", key)

    if "fiverr" in c and _CHECK_FIVERR_RE.search(c):
        return ("check_fiverr", None)

    return None


def list_summary():
    """Short spoken overview of every channel plus the live money position."""
    s = jbiz.summary()
    return (
        "Here's what we have running, sir. "
        "Fiverr: four gigs live, no orders yet. "
        "Redbubble: your shop northwichstudio with three designs up. "
        "The blog: ten articles, AdSense waiting on Google's approval, and it's now verified in Search Console. "
        f"So far £{s['revenue_total']:.2f} earned and £{s['cost_total']:.2f} spent."
    )


def chat_context():
    """
    The block injected into Jarvis's chat prompt: stable facts about each
    channel plus the live numbers from the business database.
    """
    s = jbiz.summary()
    lines = [f"BUSINESS SETUP (hand-kept snapshot as of {FACTS_AS_OF}; live details must be checked, not assumed):"]
    for channel in CHANNELS:
        lines.append(f"- {channel['name']}: {channel['what']}")
    lines.append(
        f"LIVE NUMBERS from the business database: £{s['revenue_total']:.2f} revenue, "
        f"£{s['cost_total']:.2f} spent, £{s['budget']['spent_today']:.2f} of the "
        f"£{s['budget']['daily_cap']:.2f} daily AI budget used today; "
        f"experiments by status {s['experiment_counts']}; "
        f"{len(s['pending_human_actions'])} item(s) waiting on Danny."
    )
    lines.append(
        "HOW TO MONITOR: you have your own browser (a dedicated Edge window Danny signs into once; "
        "'open the jarvis browser' opens it). 'check fiverr' reads his Fiverr orders, messages (flagging "
        "scams) and gig stats from the page text in seconds. 'agent: <task>' runs a real multi-step "
        "browser task (add 'hard' -- 'agent hard: <task>' -- to use a paid API brain if one is "
        "configured; otherwise it runs on the local model, which is weaker at long tasks). You never "
        "type passwords and never click buy/pay/publish/delete/send without Danny confirming. "
        "If Fiverr wants a login, tell Danny to sign in in the Jarvis browser window. "
        "You can also 'open fiverr orders' etc. Never invent orders, messages or earnings. "
        "Real Fiverr orders only appear on the Manage Orders page; any message claiming an order "
        "was placed, with links or attachments, is a scam. When Danny gets a real order he says "
        "'fulfil gig order: <the client's brief>' and you write the deliverable, and 'log revenue "
        "of <amount> for the gig' when he is paid. 'run a business cycle' makes you discover, "
        "score and build new ideas; 'business status' gives the numbers. The OpenAI account "
        "may be out of credit, which stops article/gig/image generation but not this chat."
    )
    return "\n".join(lines)
